### ISSUE TITLE
Maven repository does not contains .jar

### ISSUE THREAD

**Issue by zehemz** [mercadopago/dx-java#45]
Hi! I wanted to report a missing jar (or that's what I think)

Related to documentation 
http://beta.mercadopago.com.ar/developers/es/guides/payments/mobile-checkout/receive-payments/

I have tried to generate a preference. I tried to follow the configuration steps that appears here
http://beta.mercadopago.com.ar/developers/es/plugins_sdks/sdks/official/java/

and found out that the recommended pom configuration have the .jar missing

https://mvnrepository.com/artifact/com.mercadopago/dx-java/1.0.6

```
<!-- https://mvnrepository.com/artifact/com.mercadopago/dx-java -->
<dependency>
    <groupId>com.mercadopago</groupId>
    <artifactId>dx-java</artifactId>
    <version>1.0.6</version>
    <type>pom</type>
</dependency>
```

Also if I read the README.md on this repository its seems to point to a different maven artifact id (one is java-sdk and the other dx-java) that neither contain the .jar file

https://mvnrepository.com/artifact/com.mercadopago/java-sdk/1.0.6
```
<!-- https://mvnrepository.com/artifact/com.mercadopago/java-sdk -->
<dependency>
    <groupId>com.mercadopago</groupId>
    <artifactId>java-sdk</artifactId>
    <version>1.0.6</version>
</dependency>
```

The solution for me was clone the repository and add it as a module inside my project.

**Comment by joelibaceta** [comment]
Try with 

  ```xml
<dependencies>
      <dependency>
          <groupId> com.mercadopago </groupId>
          <artifactId> dx-java </artifactId>
          <version> 1.0.8 </version>
      </dependency>
  </dependencies>
```
