### ISSUE TITLE
cancel payment

### ISSUE THREAD

**Issue by toudoryca** [mercadopago/dx-java#47]
Hello!
I'm trying to cancel a payment as shown at this page https://www.mercadopago.com.mx/developers/en/guides/manage-account/cancellations-and-refunds
Payment payment = Payment.load(paymentId);
payment.setStatus("cancelled");
payment.update();

But there is no setStatus() method on Payment class. Is this a bug? Is there a workaround for canceling a payment? Thank you!

**Comment by joelibaceta** [comment]
Solved on https://github.com/mercadopago/dx-java/commit/62145674f17b5c17d6d41ca11a4e4ab4c18812ab
