### ISSUE TITLE
Unable to exclude payment types after an preference is created

### ISSUE THREAD

**Issue by toudoryca** [mercadopago/dx-java#53]
Hello. I'm trying to update the payment methods of an existing preference and the response comes with bad request.

I have tested the SDK dx-java version 1.0.10

Steps to reproduce:
1. create preference 

            MercadoPago.SDK.setClientSecret(clientSecret());
            MercadoPago.SDK.setClientId(clientId());

            Preference preference = new Preference();
            com.mercadopago.resources.datastructures.preference.Item item = new com.mercadopago.resources.datastructures.preference.Item();
            item
                    .setTitle("Rustic Bronze Shirt")
                    .setQuantity(7)
                    .setCurrencyId("MXN")
                    .setUnitPrice((float) 68.86);

            Payer payer = new Payer();
            payerDTO.setEmail("julia_powlowski@gmail.com");

            preference.setPayer(payer);
            preference.appendItem(item);
            String url = "https://requestloggerbin.herokuapp.com/bin/ac7c768c-697d-4f82-ab4d-16420046a0ba?case=";
            preference.setBackUrls(new com.mercadopago.resources.datastructures.preference.BackUrls(url + "success", url + "pending", url + "failure"));
            preference.setAutoReturn(Preference.AutoReturn.all);
            preference.setExternalReference("external_reference");

            Preference result = preference.save();

2. update existing preference. I tried all those 3 ways to update payment types

        MercadoPago.SDK.setClientSecret(clientSecret());
        MercadoPago.SDK.setClientId(clientId());
        Preference preference = getMPPreferenecById("315404205-71993487-2e04-489f-b41c-183a3f6a320e");

        //        preference.getPaymentMethods()
        //                .setExcludedPaymentTypes("credit_card");

        //        preference.getPaymentMethods()
        //                .appendExcludedPaymentTypes(new ExcludedPaymentType("credit_card"));

        preference.getPaymentMethods()
                .setExcludedPaymentTypes()
                .appendExcludedPaymentTypes(new ExcludedPaymentType("credit_card"));

        Preference result = preference.update();

Result:
In the **lastApiResponse** field of the result there are the following information:

`payload = "{"payment_methods":"{excluded_payment_methods=[{id=}], excluded_payment_types=[{id=credit_card}], installments=6.0, default_installments=3.0}"}"
statusCode = 400
reasonPhrase = "Bad Request"
stringResponse = "{"message":"payment_methods invalid. Wrong format","error":"invalid_payment_methods","status":400,"cause":[]}"
jsonElementResponse = {JsonObject@6325} "{"message":"payment_methods invalid. Wrong format","error":"invalid_payment_methods","status":400,"cause":[]}"`

Regards

**Comment by toudoryca** [comment]
Maybe this helps:

        MercadoPago.SDK.setClientSecret(clientSecret());
        MercadoPago.SDK.setClientId(clientId());
        Preference preference = Preference.findById(id);

returns a preference with payments like this:
        paymentMethods = {PaymentMethods@6389} 
         excludedPaymentMethods = {ArrayList@6406}  size = 1
          0 = {ExcludedPaymentMethod@6413} 
           id = ""
         excludedPaymentTypes = {ArrayList@6407}  size = 1
          0 = {ExcludedPaymentType@6411} 
           id = "bank_transfer"

excludedPaymentMethods contains an element with id = ""
Is it ok?

**Comment by joelibaceta** [comment]
Solved, the correct form similar to your snippet is:

```java
Preference preference = new Preference();
preference.getPaymentMethods().appendExcludedPaymentMethod(new ExcludedPaymentMethod("ExcludedPaymentMethod"));
preference.getPaymentMethods().appendExcludedPaymentTypes(new ExcludedPaymentType("ExcludedPaymentType"));
```

**Comment by joelibaceta** [comment]
Hi @ralubostan effetly we introduce a bug with last change, We was creating a PaymentMethod object after to use Get Accesor, now you have to create explicitly an PaymentMethod object if you want to use this feature:

```java
PaymentMethods paymentMethods = new PaymentMethods();
        paymentMethods.appendExcludedPaymentMethod(new ExcludedPaymentMethod().setId("ExcludedPaymentMethod"));
        paymentMethods.appendExcludedPaymentTypes(new ExcludedPaymentType().setId("ExcludedPaymentType"));
        paymentMethods.setDefaultPaymentMethodId("DefaultPaymentMethodId");
        paymentMethods.setInstallments(1);
        paymentMethods.setDefaultInstallments(1);

preference.setPaymentMethods(paymentMethods);
```

**Comment by toudoryca** [comment]
Hi @joelibaceta I tried your solution but the result is the same.
Steps to reproduce:
1. get an existing preference 
2. add some exclude payment types 
3. persist the changes. 

        //get existing preference
        Preference preference = Preference.findById("315404205-71993487-2e04-489f-b41c-183a3f6a320e");

        //update fields on preference
        PaymentMethods paymentMethods = new PaymentMethods();
        paymentMethods.appendExcludedPaymentMethod(new ExcludedPaymentMethod().setId("redlink"));
        paymentMethods.appendExcludedPaymentTypes(new ExcludedPaymentType().setId("bank_transfer"));
        paymentMethods.appendExcludedPaymentTypes(new ExcludedPaymentType().setId("atm"));

        paymentMethods.setDefaultPaymentMethodId("debit_card");
        paymentMethods.setInstallments(1);
        paymentMethods.setDefaultInstallments(1);

        preference.setPaymentMethods(paymentMethods);

        //update preference
        Preference result = preference.update();

result: 

	payload = "{"payment_methods":"{excluded_payment_methods=[{id=redlink}], excluded_payment_types=[{id=bank_transfer}, {id=atm}], default_payment_method_id=debit_card, installments=1.0, default_installments=1.0}"}"
	statusCode = 400
	reasonPhrase = "Bad Request"
	stringResponse = "{"message":"payment_methods invalid. Wrong format","error":"invalid_payment_methods","status":400,"cause":[]}"
	jsonElementResponse = {JsonObject@6325} "{"message":"payment_methods invalid. Wrong format","error":"invalid_payment_methods","status":400,"cause":[]}"

Regards

**Comment by joelibaceta** [comment]
@toudoryca are you sure are you using the last SDK version 1.0.13?, I made some tests, getting successfully responses. 
![captura de pantalla 2018-07-10 a la s 00 48 49](https://user-images.githubusercontent.com/864790/42488422-d0e54ace-83db-11e8-9696-74f4eb33e177.png)

**Comment by toudoryca** [comment]
@joelibaceta 
I tried with 1.0.13 
It works as expected for a newly created preference. But when you are trying to make those updates on an existing preference the 400-bad request is still there.

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadopago/dx-java/pull/58
