### ISSUE TITLE
How to make refund of payment?

### ISSUE THREAD

**Issue by tmacudzinski** [mercadopago/dx-java#57]
How to make refund of payment with status 'approved'?

**Comment by tmacudzinski** [comment]
I found an example of the refund ( https://www.mercadopago.com.mx/developers/en/guides/manage-account/cancellations-and-refunds ):
```
Payment payment = Payment.load(paymentId);
payment.refund(10.5);  
```
But there are no 'load' and 'refund' functions. I used 'findById' function instead of 'load', but there is no equivalent of 'refund' function. 

I'm using:
```
            <dependency>
                <groupId>com.mercadopago</groupId>
                <artifactId>dx-java</artifactId>
                <version>1.0.12</version>
            </dependency>
```

**Comment by toudoryca** [comment]
Hello. Any news on refund?
