### ISSUE TITLE
unable to expire an existing preference

### ISSUE THREAD

**Issue by toudoryca** [mercadopago/dx-java#64]
**Describe the bug**
Hi. I tried to update an existing preference in order to expire it. It returns 400 Bad Request. I am using 1.0.16 version of dx-java

**To Reproduce**
1. Run this code

        MercadoPago.SDK.setClientSecret(mpConfig.getMpClientSecret());
        MercadoPago.SDK.setClientId(mpConfig.getMpClientId());
        Preference preference = Preference.findById("315404205-da99c32c-c738-4733-9286-e991a58f77a8");
        preference.setExpires(true);
        preference.setExpirationDateFrom(new Date());
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        cal.add(Calendar.HOUR_OF_DAY, 1);
        cal.getTime();
        Date date1 = cal.getTime();
        preference.setExpirationDateTo(date1);
        Preference result = preference.update();

2. Result

payload = "{"expires":"true","expiration_date_from":"2018-09-12T19:31:31+0300","expiration_date_to":"2018-09-12T20:31:31+0300"}"

statusCode = 400

reasonPhrase = "Bad Request"

stringResponse = "{"message":"expires value is not boolean","error":"invalid_expires","status":400,"cause":[]}"

**Comment by joelibaceta** [comment]
Hi @toudoryca which version of `com.google.code.gson` are you using?

**Comment by joelibaceta** [comment]
About the version, the last SDK version available is 1.0.22

**Comment by joelibaceta** [comment]
@toudoryca we found an error building the diff between params in actual object to updated object, it was solve in https://github.com/mercadopago/dx-java/commit/a7fd5047b64975e123c7478792bf5e2fa7c3049d
