### ISSUE TITLE
Soportar el search de payments

### ISSUE THREAD

**Issue by joelibaceta** [mercadopago/dx-java#72]

**Comment by sebargarcia** [comment]
Seria bueno que maneje la paginación correctamente también

**Comment by joelibaceta** [comment]
A partir de la version 1.0.33 se soporta el search de payments.
Estamos trabajando en añadir opciones de paginado para el método search.

**Comment by sebargarcia** [comment]
Estuve viendo el código del método search de la clase Payment. Si la clase Payment también extiende de MPBase por que llamar a `Customer.processMethodBulk(Customer.class, "search", filters, useCache);` cuando debería ser `Payment.processMethodBulk(Payment.class, "search", filters, useCache);` 

Las opciones de páginado deberían respetar los párametros actuales limit y offset para el desarrollador que implemente pueda hacer uso de los mismos decidiendo el como paginar.

**Comment by joelibaceta** [comment]
@sebargarcia muchas gracias por la observación, efectivamente error mío, disculpa.
Estoy subiendo una nueva version y retirando la anterior.
