### ISSUE TITLE
How to search for a Customer?

### ISSUE THREAD

**Issue by felipebraga** [mercadopago/dx-java#74]
How to search for a Customer using SDK?

**Comment by joelibaceta** [comment]
From 1.0.33 version you have a search method

```java
HashMap<String, String> filters = new HashMap<String, String>();
filters.put("email", "name@email.com");

MPResourceArray customers = Customer.search(filters, MPBase.WITH_CACHE);
```

**Comment by joelibaceta** [comment]
We are working in a pagination options in search methods.

**Comment by felipebraga** [comment]
Hi,

It isn't working properly. I did what you sad, but when I do `Customer.search(filters, MPBase.WITH_CACHE);` I get all Customers, so the filter isn't working.

Thanks
