### ISSUE TITLE
Search Payment method should call Payment.processMethodBulk

### ISSUE THREAD

**Issue by sebargarcia** [mercadopago/dx-java#75]
**Describe the bug**
Payment class extends from MPBase so I think there is no need to call Customer.processMethodBulk . Instead it should call Payment.processMethodBulk

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadopago/dx-java/commit/c6da1065bbdc7e152f21f67c9a1809deb69041c8

**Comment by Lawiet** [comment]
Por favor corregir la clase ya que se sigue usando Customer.class en vez de Payment.class

**Comment by joelibaceta** [comment]
Ya esta corregido, disculpa nuevamente por el error
