### ISSUE TITLE
Payment::search does not add the filters to the HTTP request

### ISSUE THREAD

**Issue by franOlea** [mercadopago/dx-java#77]
When searching a **Payment** with an **external_reference** the filters do not work (brings all payments) and it doesn't appear on the api request object (Http request). After looking at the source in the class MPBase the method processMethodBulk does not use the filters at all unless there is a ":" character on the path.

I think this issue might be related to:
https://github.com/mercadopago/dx-java/issues/72
https://github.com/mercadopago/dx-java/issues/75

**Comment by escalantef** [comment]
Hi, 
I found the same issue! I want to search one customer by email and it brings me all the customers. 
It's not concat the filter in the request

**Comment by LautaroRiveiro** [comment]
Hay alguna novedad?
Gracias.

**Comment by nsolerqwork** [comment]
Tengo el mismo error, luego de actualizar la librería a v1.0.36. Pareciera haber un pull request que lo soluciona, pero no está realizado.

**Comment by delias-silva** [comment]
The issue was solved in version **1.1.0**.
