### ISSUE TITLE
create offline payment via API - 400 BAD REQUEST

### ISSUE THREAD

**Issue by juanmacugat** [mercadopago/dx-java#83]
La creacion de un pago via API para un medio de pago offline arroja 400 bad request con la siguiente descripcion:
```json
{
  "message": "Invalid parmater for the scope.",
  "error": "bad_request",
  "status": 400,
  "cause": [
    {
      "code": 2061,
      "description": "Invalid parmater for the scope.",
      "data": null
    }
  ]
}
```

**To Reproduce**

```java
  Payment payment = new Payment()
                .setTransactionAmount(100f)
                .setPayer(new Payer().setEmail("juanma.cugat@gmail.com")
                .setExternalReference(UUID.randomUUID().toString())
                .setPaymentMethodId("rapipago")
                .setDescription("Description")
                .save();

```
**Expected behavior**
Se espera que se retorne un HttpStatus code `201 CREATED` con un Payment no nulo y `status = 'pending'`

**Additional context**
Se estan utilizando credenciales (ACCESS_TOKEN) productivo. Tambien se probo en Sandbox con mismo codigo de error.

**Comment by brunitob** [comment]
Cómo lo resolvieron?
