### ISSUE TITLE
How to set the currency

### ISSUE THREAD

**Issue by mamup11** [mercadopago/dx-java#88]
Hello, I'm new integrating the Mercado Pago SDK and have a few questions about the usage and was hopping you can help me understand better the flow.

My first question is how to set the currency of the payment to COP? I saw there is a `CurrencyId` class on the `Payment` class but there is no setter method for the payment, and I was wondering how to set that info. 

Also I read that the card token is for only one usage, but I got a question about this, my current flow is: My user adds the credit card info in front end and generate a card token, I send that card token to my backend and try to do an small payment to check that the card ids real, if the payment turns out as a success I want to add that card to my Customer, but Since the card token was already used I don't know if thats possible. 

Thanks!

**Comment by delias-silva** [comment]
Hello, mamup11.

There is no way to enter currency for the Mercado Pago Api. It is associated to your user.

It is possible save a card with a token that was used for a payment.

Any other questions please contact us.
