### ISSUE TITLE
Erro to save user

### ISSUE THREAD

**Issue by ramiresnas** [mercadopago/dx-java#92]
**Describe the bug**
When I try save a user I get the error.

```
the streat_number must be a Number
```
But in `com.mercadopago.resources.datastructures.customer.DefaultAddress` the `streetNumber` is a `String`. Probably the API was a modified, because it worked before.
So, to test I did a request without using sdk and it worked.
```
{
	"email":"user_teste@email.com",
	"address":{
		"zip_code":"23233-888",
		"street_name":"the name of the street",
		"street_number": 123  <- here 
	}
}
``` 
I am using the version `1.0.33`. I too saw the new version, but has the same problem 

**Solution Proposal**
Change the type of `streetNumber` to Integer.

**Comment by delias-silva** [comment]
Fixed in version **1.2.0**.
